### ISSUE TITLE
wregex support missing?

### ISSUE THREAD

**Issue by martinrotter** [bitwiseworks/gcc-os2#17]
I get errors: "wregex is not a member of std", "regexp not declared", etc.

I compile with latest gcc 9.2.xx from experimental repository. I have C++17 standard enabled by appropriate switch.

Specifically compilling https://github.com/martinrotter/textosaurus with these steps:

```bash
cd C:\usr\bin
cp lupdate-qt5.exe lupdate.exe
cp lrelease-qt5.exe lrelease.exe
cd C:
git clone https://github.com/martinrotter/textosaurus
git submodule update --init --remote
mkdir build
cd build
qmake-qt5 ../ -r
make
```

**Comment by dmik** [comment]
Thanks for the report! You should have `std::regex` in our builds. I've just checked an example from https://en.cppreference.com/w/cpp/regex/regex_match and it gives exactly the same output under OS/2.

As of `wregex`, it's perhaps disabled at GCC configure time because of #16. Once #16 is resolved, we will get this bit too, I suppose. You have to wait for now or use the non-wide char version.

**Comment by dmik** [comment]
With the latest fixes to #16 and a full GCC rebuild, this works too, out of the box — I've modified the test case from `https://en.cppreference.com/w/cpp/regex/regex_match` to use `wregex` instead of `regex` and it works too. A new set of GCC RPMs will appear shortly.
